Git parsing
deepsourcelabs/depend pull request #123
Opened 2023-03-28 16:06 UTC by NobleMathews

Fixes #88

2023-03-29 04:18 UTC, tushar-deepsource commented
Few comments:
- Some dependencies (like in poetry, package.json) will have both a name and a repo URL. In those cases, make sure that `self.name` still has a name, not a URL. GithubDep must be instantiated with 4 arguments then, `self.name` you can keep whatever is convenient right now, if a name is available use that otherwise just keep the value you got from the dep file.
- Default branch is not to be figured out when making the `GithubDep` object. Just store the tag or ref that you get from the dep file into the object. We'll need to figure out the default branch during `raw.githubusercontent.com` based querying, and the code will be in resolver. (BTW, when you do that, use [`asyncio.subprocess.Process`](https://superfastpython.com/asyncio-subprocess))

2023-04-11 12:05 UTC, tushar-deepsource requested changes

2023-04-11 12:05 UTC, tushar-deepsource commented on src/depend/utils/npm_parser.py
> +                    dependencies.append(Dep("javascript", package, version))
Why is this indented now? We're missing cases. Like, if it's not a GitHub dep, and the version is not `latest`, we don't parse it.

2023-04-11 12:06 UTC, tushar-deepsource commented on src/depend/resolver.py
> +async def get_default_branch(dependency: GitHubDep) -> str:
Pass in the repo name here, instead of `dependency`, and then add a `@cache` decorator on this function to avoid duplicate work.

2023-04-11 12:07 UTC, tushar-deepsource commented on src/depend/resolver.py
> +async def get_default_branch(dependency: GitHubDep) -> str:
Also don't depend on `awk`, regex the output and use that if possible.

2023-04-12 12:23 UTC, tushar-deepsource commented on src/depend/resolver.py
> +        return "main"
Does this case happen in reality?

2023-04-12 12:54 UTC, NobleMathews commented on src/depend/resolver.py
> +        return "main"
Don't think so, I haven't seen it happen yet

2023-04-12 13:16 UTC, tushar-deepsource commented on src/depend/utils/python.py
> +                    named = None
Refactoring this, it's confusing as it is now.

2023-04-13 09:59 UTC, merged